version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - huphtur
  ignore:
  - dependency-name: cssnano
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
    - 10.2.5
  - dependency-name: postcss-cli
    versions:
    - 8.3.1
